"""
Each new term in the Fibonacci sequence is generated by
adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values
do notexceed four million, find the sum of the even-valued terms.
"""

numrange = 4e6

a=1
b=2
count =2
currentsum = 0

while b < numrange:
    a,b=b,a+b
    count +=1
    if a%2 == 0:
        currentsum = currentsum + a

print currentsum
